baseURL = "https://jern.me/"
languageCode = "sv-FI"
title = "Blog"
theme = "no-js"

[params]
  # enable javascript theme switcher
  themeStyleSwitcher = true # default false
  # theme style if the theme switcher is disabled
  #themeStyle = "dark.css" # default "light.css"
  # footer text at the bottom of every page
  footerText = "Min personliga blog. Byggd med [Hugo](https://gohugo.io/) och [no-js-hugo-theme](https://github.com/stevenengler/no-js-hugo-theme)."
  # enable the table of content on pages with more than this many words (negative to disable)
  # (can be overridden per-page by setting the 'toc' front matter parameter)
  #tocWordThreshold = 1000 # default <unset>
